name: "Check Latest Release Badge"
description: "Check the latest release and generate a badge for README.md"
inputs:
  repo:
    description: "Repository to check for latest release"
    required: true
    default: "owner/repo" # replace with your repository by default
  token:
    description: "GitHub token"
    required: true

outputs:
  badge_url:
    description: "URL for the Shields.io badge"

runs:
  using: "node20"
  main: "dist/index.js"

branding:
  icon: "box"
  color: "gray-dark"
