name: Test Action and publish url to artifact

on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  test:
    name: Test publishing badge
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Extract version tag
        id: extract_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        
      - name: Check latest release and get badge URL
        uses: aliciousness/ACTION-latest-release-badge@main
        id: check_release
        with:
          repo: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Save badge URL to file
        run: echo "${{ steps.check_release.outputs.badge_url }}" > badge_url

      - name: Upload badge URL as artifact
        uses: actions/upload-artifact@v4
        with:
          name: badge_url
          path: badge_url
          
      - name: Read it out to summary
        run: echo "[${{ steps.check_release.outputs.badge_url }}](https://github.com/aliciousness/ACTION-latest-release-badge/releases/${{ env.TAG }})" >> $GITHUB_STEP_SUMMARY
